// Knowledge Tree — a map of the Rust landscape, curriculum overlaid on top.
//
// Included by the HTML dashboard via `#[path = "../knowledge_tree.rs"] mod knowledge_tree;`
// — the repo has no lib.rs on purpose (see CLAUDE.md), so this follows the same
// `#[path]` convention used by tracker.rs, src/lesson32, and c74 -> c71.
//
// DASHBOARD-ONLY. `progress` and `tracker.rs` know nothing about this file.
//
// Unlike tracker.rs's LESSONS, this is deliberately WIDER than the 80-lesson track:
// most nodes carry an empty `lessons` slice, meaning "real Rust, not taught here".
// That is the point — the panel renders three states (learned / queued / uncharted)
// so the learner can see the curriculum's footprint against the whole language.
//
// Every `parent` is an `id` that exists in this array; roots carry `None`.
// Names and blurbs are full of `Option<T>`, `Box<dyn Trait>`, `extern "C"` and the
// like — the dashboard MUST run all of them through `esc()` before writing HTML.
#![allow(dead_code)]

pub struct KTNode {
    pub id: &'static str,
    pub parent: Option<&'static str>,
    pub name: &'static str,
    pub blurb: &'static str,
    pub lessons: &'static [u32],
}

/// 223 nodes: 8 top-level branches plus their subtrees.
#[rustfmt::skip]
pub const KNOWLEDGE_TREE: &[KTNode] = &[

    // ── Language Core & Type System ──
    KTNode { id: "language", parent: None, name: "Language Core & Type System", blurb: "Syntax, control flow, structs/enums/traits, generics, and the type-system machinery that makes Rust Rust.", lessons: &[] },
    KTNode { id: "language.variables-bindings", parent: Some("language"), name: "Variables & Bindings", blurb: "let bindings, mutability (mut), shadowing, and const/static declarations.", lessons: &[1] },
    KTNode { id: "language.primitive-types", parent: Some("language"), name: "Primitive Types, Tuples & Casting", blurb: "Integers, floats, bool, char, and tuples, plus explicit numeric conversion with as casts.", lessons: &[4] },
    KTNode { id: "language.control-flow", parent: Some("language"), name: "Control Flow", blurb: "if/else branching and for/while/loop iteration constructs.", lessons: &[5] },
    KTNode { id: "language.functions", parent: Some("language"), name: "Functions", blurb: "Function declarations, parameters, return values, recursion, and free functions vs. methods.", lessons: &[55] },
    KTNode { id: "language.closures", parent: Some("language"), name: "Closures", blurb: "Anonymous functions that capture their environment, distinguished by Fn/FnMut/FnOnce.", lessons: &[20] },
    KTNode { id: "language.structs", parent: Some("language"), name: "Structs", blurb: "Named-field, tuple, and unit structs for grouping related data.", lessons: &[9] },
    KTNode { id: "language.methods-impl", parent: Some("language"), name: "Methods & impl Blocks", blurb: "impl blocks define methods and associated functions on a type.", lessons: &[10] },
    KTNode { id: "language.enums", parent: Some("language"), name: "Enums", blurb: "Algebraic sum types with variants, the backbone of exhaustive matching.", lessons: &[11] },
    KTNode { id: "language.pattern-matching", parent: Some("language"), name: "Pattern Matching", blurb: "match expressions, destructuring, guards, and binding patterns.", lessons: &[6] },
    KTNode { id: "language.question-operator", parent: Some("language"), name: "The ? Operator", blurb: "Propagates Err/None early, desugaring to an early return from the function.", lessons: &[18] },
    KTNode { id: "language.modules", parent: Some("language"), name: "Modules & Visibility", blurb: "mod, use, and pub control how code is organized into a module tree and what each layer exposes.", lessons: &[32, 33] },
    KTNode { id: "language.traits", parent: Some("language"), name: "Traits", blurb: "Shared behavior contracts a type can implement, Rust's answer to interfaces.", lessons: &[26] },
    KTNode { id: "language.traits.trait-objects", parent: Some("language.traits"), name: "Trait Objects (dyn Trait)", blurb: "Runtime polymorphism via vtables with Box<dyn Trait>, versus static dispatch with generics.", lessons: &[57] },
    KTNode { id: "language.generics", parent: Some("language"), name: "Generics", blurb: "Type parameters that let functions and structs work over many concrete types.", lessons: &[27] },
    KTNode { id: "language.generics.trait-bounds", parent: Some("language.generics"), name: "Trait Bounds", blurb: "Constraining generic parameters with trait bounds, where clauses, and impl Trait.", lessons: &[28] },
    KTNode { id: "language.associated-types", parent: Some("language"), name: "Associated Types", blurb: "Type placeholders declared inside a trait definition, resolved by each implementor.", lessons: &[] },
    KTNode { id: "language.associated-types.gats", parent: Some("language.associated-types"), name: "Generic Associated Types (GATs)", blurb: "Associated types that themselves take lifetime, type, or const parameters; stable since Rust 1.65.", lessons: &[] },
    KTNode { id: "language.operator-overloading", parent: Some("language"), name: "Operator Overloading", blurb: "Implementing std ops traits (Add, Index, From/Into) to give custom types operator syntax.", lessons: &[] },
    KTNode { id: "language.const-generics", parent: Some("language"), name: "Const Generics", blurb: "Generic parameters that are values, not types, e.g. arrays parameterized by [T; N].", lessons: &[] },
    KTNode { id: "language.higher-ranked-trait-bounds", parent: Some("language"), name: "Higher-Ranked Trait Bounds", blurb: "for<'a> bounds that quantify over all possible lifetimes, mostly seen with fn/closure traits.", lessons: &[] },
    KTNode { id: "language.variance", parent: Some("language"), name: "Variance", blurb: "How subtyping of lifetimes and types propagates through generics and references (co/contra/invariant).", lessons: &[] },
    KTNode { id: "language.never-type", parent: Some("language"), name: "The Never Type (!)", blurb: "The type of computations that never return, used by panic!, loop, and diverging match arms.", lessons: &[] },
    KTNode { id: "language.newtype-pattern", parent: Some("language"), name: "Newtype Pattern", blurb: "Wrapping a type in a tuple struct to get a distinct type and work around the orphan rule.", lessons: &[] },
    KTNode { id: "language.phantom-types-zst", parent: Some("language"), name: "PhantomData & Zero-Sized Types", blurb: "PhantomData and zero-sized types encode compile-time-only information with no runtime cost.", lessons: &[] },
    KTNode { id: "language.typestate-pattern", parent: Some("language"), name: "Typestate Pattern", blurb: "Encoding an object's valid states in its type so illegal state transitions fail to compile.", lessons: &[] },
    KTNode { id: "language.editions", parent: Some("language"), name: "Language Editions", blurb: "Opt-in editions (2015/2018/2021/2024) that evolve syntax and defaults without breaking old crates.", lessons: &[] },

    // ── Ownership, Memory & Lifetimes ──
    KTNode { id: "memory", parent: None, name: "Ownership, Memory & Lifetimes", blurb: "The borrow checker's domain: ownership, moves, lifetimes, smart pointers, interior mutability, and RAII.", lessons: &[] },
    KTNode { id: "memory.ownership", parent: Some("memory"), name: "Ownership Rules", blurb: "Every value has exactly one owner; when the owner goes out of scope, the value is dropped.", lessons: &[7] },
    KTNode { id: "memory.borrowing", parent: Some("memory"), name: "Borrowing", blurb: "Shared (&T) and exclusive (&mut T) references let code access data without taking ownership.", lessons: &[7] },
    KTNode { id: "memory.move-semantics", parent: Some("memory"), name: "Move Semantics", blurb: "Assigning or passing a non-Copy value transfers ownership and invalidates the source binding.", lessons: &[7] },
    KTNode { id: "memory.copy-clone", parent: Some("memory"), name: "Copy and Clone", blurb: "Copy gives implicit bitwise duplication for simple types; Clone provides explicit, possibly expensive duplication.", lessons: &[] },
    KTNode { id: "memory.lifetimes", parent: Some("memory"), name: "Lifetimes", blurb: "Named lifetime parameters let the compiler verify references never outlive the data they point to.", lessons: &[29] },
    KTNode { id: "memory.lifetimes.elision", parent: Some("memory.lifetimes"), name: "Lifetime Elision", blurb: "Compiler-applied rules infer lifetime annotations in common function signatures so you can omit them.", lessons: &[41] },
    KTNode { id: "memory.lifetimes.struct-lifetimes", parent: Some("memory.lifetimes"), name: "Struct Lifetimes", blurb: "Structs holding references need lifetime parameters tying the struct's validity to the borrowed data.", lessons: &[40] },
    KTNode { id: "memory.smart-pointers", parent: Some("memory"), name: "Smart Pointers", blurb: "Types that own heap data and add behavior such as dispatch, shared ownership, or weak refs on top of a pointer.", lessons: &[] },
    KTNode { id: "memory.smart-pointers.box", parent: Some("memory.smart-pointers"), name: "Box<T>", blurb: "Box<T> is a single-owner heap allocation, used for recursive types and Box<dyn Trait> trait objects.", lessons: &[30, 56, 57] },
    KTNode { id: "memory.smart-pointers.rc", parent: Some("memory.smart-pointers"), name: "Rc<T>", blurb: "Rc<T> is a single-threaded reference-counted pointer enabling multiple owners of the same heap data.", lessons: &[31, 44] },
    KTNode { id: "memory.smart-pointers.arc", parent: Some("memory.smart-pointers"), name: "Arc<T>", blurb: "Arc<T> is Rc's atomically-reference-counted, thread-safe counterpart for sharing data across threads.", lessons: &[66, 67] },
    KTNode { id: "memory.smart-pointers.weak", parent: Some("memory.smart-pointers"), name: "Weak<T>", blurb: "Weak<T> is a non-owning reference into Rc/Arc data that breaks reference cycles and can be upgraded to check liveness.", lessons: &[61] },
    KTNode { id: "memory.smart-pointers.deref", parent: Some("memory.smart-pointers"), name: "Deref / DerefMut", blurb: "The Deref/DerefMut traits let custom smart pointers behave like references via auto-deref and the . operator.", lessons: &[58] },
    KTNode { id: "memory.smart-pointers.cow", parent: Some("memory.smart-pointers"), name: "Cow<'a, T>", blurb: "Cow<'a, T> defers cloning until mutation is needed, borrowing when possible and owning only when it must.", lessons: &[] },
    KTNode { id: "memory.interior-mutability", parent: Some("memory"), name: "Interior Mutability", blurb: "Types that allow mutating data through a shared reference by moving borrow checks to runtime or using atomics.", lessons: &[] },
    KTNode { id: "memory.interior-mutability.cell", parent: Some("memory.interior-mutability"), name: "Cell<T>", blurb: "Cell<T> allows get/set replacement of a Copy value through a shared reference with zero runtime checks.", lessons: &[42, 63] },
    KTNode { id: "memory.interior-mutability.refcell", parent: Some("memory.interior-mutability"), name: "RefCell<T>", blurb: "RefCell<T> enforces Rust's borrow rules at runtime, panicking on conflicting borrows instead of failing to compile.", lessons: &[43, 44, 64, 79] },
    KTNode { id: "memory.interior-mutability.oncecell", parent: Some("memory.interior-mutability"), name: "OnceCell / OnceLock / LazyLock", blurb: "These initialize a value exactly once, lazily; LazyLock/OnceLock (stable since 1.80) replace lazy_static in most cases.", lessons: &[] },
    KTNode { id: "memory.unsafecell", parent: Some("memory"), name: "UnsafeCell<T>", blurb: "UnsafeCell<T> is the sole primitive that legally allows mutation through a shared reference; all interior mutability builds on it.", lessons: &[] },
    KTNode { id: "memory.drop-raii", parent: Some("memory"), name: "Drop / RAII", blurb: "The Drop trait runs custom cleanup code when a value goes out of scope, the basis of Rust's RAII pattern.", lessons: &[60] },
    KTNode { id: "memory.memory-layout", parent: Some("memory"), name: "Memory Layout", blurb: "How Rust lays out struct and enum fields in memory, and the attributes that control that layout.", lessons: &[] },
    KTNode { id: "memory.memory-layout.repr", parent: Some("memory.memory-layout"), name: "repr(C) / repr(Rust) / repr(transparent)", blurb: "repr(Rust) is the default unspecified layout; repr(C) gives C-compatible layout for FFI; repr(transparent) wraps one field.", lessons: &[] },
    KTNode { id: "memory.memory-layout.alignment", parent: Some("memory.memory-layout"), name: "Alignment & Padding", blurb: "Every type has a size and alignment; padding is inserted between fields so each satisfies its alignment requirement.", lessons: &[] },
    KTNode { id: "memory.memory-layout.niche-optimization", parent: Some("memory.memory-layout"), name: "Niche Optimization", blurb: "The compiler packs enum tags into unused bit patterns, e.g. Option<&T> has the same size as &T.", lessons: &[] },
    KTNode { id: "memory.stack-vs-heap", parent: Some("memory"), name: "Stack vs Heap", blurb: "Stack allocation is fast and scope-bound; heap allocation (via Box, Vec, String) is flexible but needs indirection.", lessons: &[] },

    // ── Standard Library & Collections ──
    KTNode { id: "stdlib", parent: None, name: "Standard Library & Collections", blurb: "Vec/String/HashMap and friends, iterators, Option/Result, formatting, and std I/O.", lessons: &[] },
    KTNode { id: "stdlib.string", parent: Some("stdlib"), name: "String and &str", blurb: "Owned, growable String vs. borrowed &str views over UTF-8 text, plus common string methods.", lessons: &[2, 6, 8, 15] },
    KTNode { id: "stdlib.arrays", parent: Some("stdlib"), name: "Arrays", blurb: "Fixed-size, stack-allocated [T; N] collections with a compile-time-known length.", lessons: &[3] },
    KTNode { id: "stdlib.slices", parent: Some("stdlib"), name: "Slices", blurb: "Borrowed, dynamically-sized views &[T]/&str into contiguous data; the backbone of safe indexing.", lessons: &[8, 39, 78] },
    KTNode { id: "stdlib.vec", parent: Some("stdlib"), name: "Vec<T>", blurb: "Growable, heap-allocated, contiguous array type; Rust's default general-purpose collection.", lessons: &[62] },
    KTNode { id: "stdlib.collections", parent: Some("stdlib"), name: "Collections", blurb: "std::collections module: the map/set/queue/heap types beyond Vec, each with different ordering and performance tradeoffs.", lessons: &[] },
    KTNode { id: "stdlib.collections.hashmap", parent: Some("stdlib.collections"), name: "HashMap", blurb: "Unordered key-value map with O(1) average lookup; the entry API drives insert-or-update patterns.", lessons: &[13, 14, 16, 59, 75] },
    KTNode { id: "stdlib.collections.btreemap", parent: Some("stdlib.collections"), name: "BTreeMap", blurb: "Ordered key-value map backed by a B-tree; keeps keys sorted for range queries and iteration.", lessons: &[] },
    KTNode { id: "stdlib.collections.sets", parent: Some("stdlib.collections"), name: "HashSet and BTreeSet", blurb: "Set types built on HashMap/BTreeMap internals; unordered vs sorted membership collections.", lessons: &[65] },
    KTNode { id: "stdlib.collections.vecdeque", parent: Some("stdlib.collections"), name: "VecDeque", blurb: "Ring-buffer double-ended queue with O(1) push/pop at both ends; std's preferred FIFO/LIFO type.", lessons: &[] },
    KTNode { id: "stdlib.collections.binaryheap", parent: Some("stdlib.collections"), name: "BinaryHeap", blurb: "Max-heap priority queue with O(log n) push/pop and O(1) peek at the largest element.", lessons: &[] },
    KTNode { id: "stdlib.collections.linkedlist", parent: Some("stdlib.collections"), name: "LinkedList", blurb: "Doubly-linked list; std's own docs recommend Vec or VecDeque instead for almost all use cases.", lessons: &[] },
    KTNode { id: "stdlib.option-result", parent: Some("stdlib"), name: "Option and Result", blurb: "The two core enums for absence and fallibility, with combinator methods for chaining logic.", lessons: &[] },
    KTNode { id: "stdlib.option-result.option", parent: Some("stdlib.option-result"), name: "Option<T>", blurb: "Represents an optional value with no null; pattern-match or use combinator methods to handle None.", lessons: &[12] },
    KTNode { id: "stdlib.option-result.result-propagation", parent: Some("stdlib.option-result"), name: "Result<T, E> and ?", blurb: "Represents success or failure explicitly; the ? operator and map_err propagate and transform errors.", lessons: &[17, 18, 19, 76] },
    KTNode { id: "stdlib.iterator", parent: Some("stdlib"), name: "Iterator Trait Family", blurb: "The lazy, composable Iterator trait and its adaptor/consumer methods that power for-loops and pipelines.", lessons: &[] },
    KTNode { id: "stdlib.iterator.transform-adaptors", parent: Some("stdlib.iterator"), name: "map, filter, collect", blurb: "Lazy adaptors that transform or select elements, materialized into a collection with collect.", lessons: &[21, 22, 77] },
    KTNode { id: "stdlib.iterator.consuming-adaptors", parent: Some("stdlib.iterator"), name: "sum, fold, and reducers", blurb: "Terminal iterator methods that consume the sequence into a single aggregated value.", lessons: &[23, 24] },
    KTNode { id: "stdlib.iterator.custom-iterator", parent: Some("stdlib.iterator"), name: "Custom Iterator impl", blurb: "Implementing the Iterator trait's next() method to make your own type iterable.", lessons: &[45] },
    KTNode { id: "stdlib.iterator.adaptors-library", parent: Some("stdlib.iterator"), name: "Iterator Adaptors Library", blurb: "Built-in chaining adaptors like chain, zip, enumerate, take, and skip for composing pipelines.", lessons: &[46] },
    KTNode { id: "stdlib.intoiterator", parent: Some("stdlib"), name: "IntoIterator", blurb: "The trait that lets for-loops consume any type by converting it into an iterator.", lessons: &[] },
    KTNode { id: "stdlib.fmt", parent: Some("stdlib"), name: "std::fmt (Display/Debug)", blurb: "Formatting traits and macros (format!, println!) behind Display, Debug, and derive(Debug).", lessons: &[2, 25] },
    KTNode { id: "stdlib.io", parent: Some("stdlib"), name: "std::io", blurb: "Read/Write traits plus BufReader/BufWriter for buffered, byte-oriented I/O over files and streams.", lessons: &[] },
    KTNode { id: "stdlib.env-process", parent: Some("stdlib"), name: "std::env and std::process", blurb: "Reading CLI args and environment variables, and spawning, exiting, or inspecting child processes.", lessons: &[] },
    KTNode { id: "stdlib.time", parent: Some("stdlib"), name: "std::time", blurb: "Duration, Instant, and SystemTime for measuring elapsed time and wall-clock timestamps.", lessons: &[] },
    KTNode { id: "stdlib.error-handling", parent: Some("stdlib"), name: "Error Handling Ecosystem", blurb: "std::error::Error plus the crates (thiserror, anyhow, eyre) that make error types ergonomic.", lessons: &[] },
    KTNode { id: "stdlib.error-handling.custom-error-types", parent: Some("stdlib.error-handling"), name: "Custom Error Types", blurb: "Hand-rolling an error enum with Display and std::error::Error impls for library-quality errors.", lessons: &[34, 35, 36] },
    KTNode { id: "stdlib.error-handling.thiserror", parent: Some("stdlib.error-handling"), name: "thiserror", blurb: "Derive macro that generates Display and Error impls for custom error enums; the library-crate standard.", lessons: &[37] },
    KTNode { id: "stdlib.error-handling.anyhow", parent: Some("stdlib.error-handling"), name: "anyhow", blurb: "Type-erased, dynamic error type with .context() for application code that just needs to report errors.", lessons: &[38] },
    KTNode { id: "stdlib.error-handling.eyre", parent: Some("stdlib.error-handling"), name: "eyre", blurb: "A fork of anyhow with customizable, colorful error reports; popular for CLI application errors.", lessons: &[] },
    KTNode { id: "stdlib.derive-traits", parent: Some("stdlib"), name: "Common Derive Traits", blurb: "derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Default) auto-implements std comparison and utility traits.", lessons: &[] },

    // ── Concurrency & Async ──
    KTNode { id: "concurrency", parent: None, name: "Concurrency & Async", blurb: "Threads, sync primitives, async/await, futures, and the runtimes (tokio, async-std) that drive them.", lessons: &[] },
    KTNode { id: "concurrency.threads", parent: Some("concurrency"), name: "std::thread", blurb: "OS-level threads via thread::spawn, with JoinHandle for joining and returning results.", lessons: &[66] },
    KTNode { id: "concurrency.threads.scoped", parent: Some("concurrency.threads"), name: "Scoped threads", blurb: "std::thread::scope lets threads borrow stack data safely without Arc, guaranteed to join before returning.", lessons: &[] },
    KTNode { id: "concurrency.threads.builder", parent: Some("concurrency.threads"), name: "thread::Builder", blurb: "Configures a thread's name and stack size before spawning it.", lessons: &[] },
    KTNode { id: "concurrency.send-sync", parent: Some("concurrency"), name: "Send and Sync", blurb: "Auto marker traits the compiler uses to statically forbid data races across threads.", lessons: &[66, 67, 68] },
    KTNode { id: "concurrency.mutex-rwlock", parent: Some("concurrency"), name: "Mutex and RwLock", blurb: "std::sync primitives for exclusive or reader/writer locked access to shared state.", lessons: &[67, 68] },
    KTNode { id: "concurrency.mutex-rwlock.arc-mutex", parent: Some("concurrency.mutex-rwlock"), name: "Arc<Mutex<T>> pattern", blurb: "The idiomatic combo for shared mutable state across threads: Arc for ownership, Mutex for access.", lessons: &[67] },
    KTNode { id: "concurrency.mutex-rwlock.poisoning", parent: Some("concurrency.mutex-rwlock"), name: "Lock poisoning", blurb: "A Mutex/RwLock is marked poisoned if a thread panics while holding it, surfacing as an Err on lock().", lessons: &[] },
    KTNode { id: "concurrency.condvar", parent: Some("concurrency"), name: "Condvar", blurb: "std::sync::Condvar lets threads block until notified, typically paired with a Mutex-guarded condition.", lessons: &[] },
    KTNode { id: "concurrency.channels", parent: Some("concurrency"), name: "mpsc channels", blurb: "std::sync::mpsc gives multi-producer single-consumer message passing between threads.", lessons: &[] },
    KTNode { id: "concurrency.channels.crossbeam-channel", parent: Some("concurrency.channels"), name: "crossbeam-channel", blurb: "A faster, richer channel crate supporting multi-producer multi-consumer and select! over channels.", lessons: &[] },
    KTNode { id: "concurrency.channels.async-channels", parent: Some("concurrency.channels"), name: "tokio::sync channels", blurb: "Async-aware mpsc, oneshot, broadcast, and watch channels for passing messages between tasks.", lessons: &[52, 80] },
    KTNode { id: "concurrency.atomics", parent: Some("concurrency"), name: "Atomic types", blurb: "std::sync::atomic (AtomicUsize, AtomicBool, etc.) for lock-free shared counters and flags with explicit memory ordering.", lessons: &[] },
    KTNode { id: "concurrency.crossbeam", parent: Some("concurrency"), name: "crossbeam", blurb: "A crate family of lock-free data structures, scoped threads, and epoch-based memory reclamation for concurrent Rust.", lessons: &[] },
    KTNode { id: "concurrency.crossbeam.epoch", parent: Some("concurrency.crossbeam"), name: "crossbeam-epoch", blurb: "Epoch-based garbage collection enabling safe lock-free data structures without a tracing GC.", lessons: &[] },
    KTNode { id: "concurrency.rayon", parent: Some("concurrency"), name: "rayon", blurb: "A data-parallelism library that turns iterators into parallel work-stealing computations with par_iter().", lessons: &[] },
    KTNode { id: "concurrency.loom", parent: Some("concurrency"), name: "loom", blurb: "A permutation-testing tool from the Tokio project that exhaustively explores thread interleavings to catch race bugs.", lessons: &[] },
    KTNode { id: "concurrency.async-fundamentals", parent: Some("concurrency"), name: "async/await fundamentals", blurb: "async fn and .await desugar to state machines implementing Future, Rust's cooperative concurrency model.", lessons: &[50] },
    KTNode { id: "concurrency.future-trait", parent: Some("concurrency"), name: "The Future trait", blurb: "The core std::future::Future trait with its poll method, driven by an executor to make progress.", lessons: &[50] },
    KTNode { id: "concurrency.pinning", parent: Some("concurrency"), name: "Pin and Unpin", blurb: "Pin<P> prevents self-referential async state machines and other pinned values from being moved in memory after polling starts.", lessons: &[] },
    KTNode { id: "concurrency.async-in-traits", parent: Some("concurrency"), name: "async fn in traits", blurb: "Native async trait methods (stable since 1.75) for static dispatch; async-trait crate is now only needed for dyn trait objects.", lessons: &[] },
    KTNode { id: "concurrency.runtimes", parent: Some("concurrency"), name: "Async runtimes", blurb: "Executors that poll futures to completion; Rust's std library ships no runtime of its own.", lessons: &[50] },
    KTNode { id: "concurrency.runtimes.tokio", parent: Some("concurrency.runtimes"), name: "tokio", blurb: "The de facto standard multi-threaded async runtime, with spawn, timers, I/O, and a large ecosystem.", lessons: &[50, 51, 52, 80] },
    KTNode { id: "concurrency.runtimes.smol", parent: Some("concurrency.runtimes"), name: "smol", blurb: "A small, modular async runtime; the ecosystem's consolidation point after async-std's 2025 discontinuation.", lessons: &[] },
    KTNode { id: "concurrency.futures-crate", parent: Some("concurrency"), name: "futures crate", blurb: "Utility crate providing Stream, combinators, and executor-agnostic helpers layered on std::future::Future.", lessons: &[] },
    KTNode { id: "concurrency.streams", parent: Some("concurrency"), name: "Stream trait", blurb: "The async counterpart to Iterator, yielding a sequence of values over time via poll_next.", lessons: &[] },
    KTNode { id: "concurrency.macros", parent: Some("concurrency"), name: "select! and join!", blurb: "Macros (from tokio/futures) to race multiple futures to first completion or await several concurrently.", lessons: &[] },
    KTNode { id: "concurrency.actors", parent: Some("concurrency"), name: "Actor-model crates", blurb: "Message-passing concurrency frameworks (actix, kameo, ractor, coerce, xtra) built atop async tasks and channels.", lessons: &[] },
    KTNode { id: "concurrency.cancellation", parent: Some("concurrency"), name: "Cancellation and structured concurrency", blurb: "Patterns like CancellationToken, JoinSet, and select! to cancel or bound the lifetime of spawned async work.", lessons: &[] },

    // ── Macros, Unsafe & FFI ──
    KTNode { id: "meta-unsafe", parent: None, name: "Macros, Unsafe & FFI", blurb: "Metaprogramming with macro_rules!/proc-macros, and the unsafe/FFI layer for talking to C and hardware.", lessons: &[] },
    KTNode { id: "meta-unsafe.declarative-macros", parent: Some("meta-unsafe"), name: "Declarative Macros (macro_rules!)", blurb: "Pattern-matching macros defined with macro_rules! that expand token trees into repeated or templated code.", lessons: &[] },
    KTNode { id: "meta-unsafe.declarative-macros.hygiene-and-repetition", parent: Some("meta-unsafe.declarative-macros"), name: "Macro Hygiene & Repetition", blurb: "How macro_rules! matchers, $()* repetition, and identifier hygiene control what expanded code can see.", lessons: &[] },
    KTNode { id: "meta-unsafe.proc-macros", parent: Some("meta-unsafe"), name: "Procedural Macros", blurb: "Compiler-plugin-style macros that run arbitrary Rust code over token streams at compile time.", lessons: &[] },
    KTNode { id: "meta-unsafe.proc-macros.derive-macros", parent: Some("meta-unsafe.proc-macros"), name: "Custom Derive Macros", blurb: "proc_macro_derive macros like those behind #[derive(Serialize)] that generate trait impls from structs/enums.", lessons: &[] },
    KTNode { id: "meta-unsafe.proc-macros.attribute-macros", parent: Some("meta-unsafe.proc-macros"), name: "Attribute Macros", blurb: "proc_macro_attribute macros such as #[tokio::main] that rewrite the item they annotate.", lessons: &[] },
    KTNode { id: "meta-unsafe.proc-macros.function-like-macros", parent: Some("meta-unsafe.proc-macros"), name: "Function-like Proc Macros", blurb: "proc_macro macros invoked like sql!(...) that parse arbitrary custom syntax inside the parentheses.", lessons: &[] },
    KTNode { id: "meta-unsafe.proc-macros.syn-quote", parent: Some("meta-unsafe.proc-macros"), name: "syn, quote & proc-macro2", blurb: "The standard toolchain for writing proc macros: syn parses tokens to an AST, quote turns it back into code.", lessons: &[] },
    KTNode { id: "meta-unsafe.build-scripts", parent: Some("meta-unsafe"), name: "Build Scripts (build.rs)", blurb: "Cargo-invoked build.rs programs that generate code, compile C libraries, or set cfg flags before the crate builds.", lessons: &[] },
    KTNode { id: "meta-unsafe.unsafe-rust", parent: Some("meta-unsafe"), name: "Unsafe Rust Fundamentals", blurb: "The unsafe keyword's superpowers: raw pointer deref, unsafe fn calls, mutable statics, unions, unsafe traits.", lessons: &[] },
    KTNode { id: "meta-unsafe.unsafe-rust.raw-pointers", parent: Some("meta-unsafe.unsafe-rust"), name: "Raw Pointers (*const/*mut)", blurb: "Unchecked pointer types with pointer arithmetic and manual aliasing rules, unlike references.", lessons: &[] },
    KTNode { id: "meta-unsafe.unsafe-rust.unsafe-traits", parent: Some("meta-unsafe.unsafe-rust"), name: "Unsafe Traits & Impls", blurb: "Traits like Send and Sync whose contracts the compiler cannot verify, so implementing them requires unsafe impl.", lessons: &[] },
    KTNode { id: "meta-unsafe.unsafe-rust.undefined-behavior", parent: Some("meta-unsafe.unsafe-rust"), name: "Undefined Behavior Rules", blurb: "The catalog of UB in Rust - invalid values, data races, aliasing violations - that unsafe code must avoid.", lessons: &[] },
    KTNode { id: "meta-unsafe.transmute-and-layout", parent: Some("meta-unsafe"), name: "transmute & Memory Layout", blurb: "mem::transmute, size_of/align_of, and the layout guarantees unsafe code relies on to reinterpret bytes safely.", lessons: &[] },
    KTNode { id: "meta-unsafe.ffi", parent: Some("meta-unsafe"), name: "FFI (extern \"C\")", blurb: "Declaring and calling C functions across the language boundary with extern blocks and calling conventions.", lessons: &[] },
    KTNode { id: "meta-unsafe.ffi.bindgen-cbindgen", parent: Some("meta-unsafe.ffi"), name: "bindgen & cbindgen", blurb: "Codegen tools that auto-generate Rust bindings from C headers (bindgen) or C headers from Rust (cbindgen).", lessons: &[] },
    KTNode { id: "meta-unsafe.ffi.cxx-crate", parent: Some("meta-unsafe.ffi"), name: "cxx Crate (C++ Interop)", blurb: "A safe-by-construction bridge for calling C++ from Rust and vice versa, avoiding raw extern \"C\" pitfalls.", lessons: &[] },
    KTNode { id: "meta-unsafe.ffi.callback-closures", parent: Some("meta-unsafe.ffi"), name: "FFI Callbacks & Function Pointers", blurb: "Passing Rust closures across the FFI boundary as extern \"C\" fn pointers plus a void* context argument.", lessons: &[] },
    KTNode { id: "meta-unsafe.allocator-api", parent: Some("meta-unsafe"), name: "Allocator API", blurb: "The GlobalAlloc trait and #[global_allocator] attribute for swapping in a custom heap allocator.", lessons: &[] },
    KTNode { id: "meta-unsafe.inline-asm", parent: Some("meta-unsafe"), name: "Inline Assembly (asm!)", blurb: "The asm! and naked_asm! macros for embedding architecture-specific machine instructions directly in Rust.", lessons: &[] },

    // ── Tooling, Testing & Quality ──
    KTNode { id: "tooling", parent: None, name: "Tooling, Testing & Quality", blurb: "Cargo, clippy, rustfmt, testing, benchmarking, fuzzing, miri, and the workflow around writing correct Rust.", lessons: &[] },
    KTNode { id: "tooling.cargo", parent: Some("tooling"), name: "Cargo", blurb: "Rust's build tool and package manager: compiles crates, resolves dependencies via Cargo.toml/Cargo.lock, runs tests and binaries.", lessons: &[] },
    KTNode { id: "tooling.cargo.workspaces", parent: Some("tooling.cargo"), name: "Cargo Workspaces", blurb: "Multiple crates sharing one Cargo.lock and target directory, declared by a top-level [workspace] in Cargo.toml.", lessons: &[] },
    KTNode { id: "tooling.cargo.features", parent: Some("tooling.cargo"), name: "Cargo Features", blurb: "Named flags in Cargo.toml that turn optional dependencies and code paths on or off at compile time.", lessons: &[] },
    KTNode { id: "tooling.cargo.profiles", parent: Some("tooling.cargo"), name: "Cargo Profiles", blurb: "Named build configs (dev, release, custom) controlling optimization level, debug info, LTO, and panic strategy.", lessons: &[] },
    KTNode { id: "tooling.cargo.publishing", parent: Some("tooling.cargo"), name: "Publishing to crates.io", blurb: "Versioning with semver, filling in crate metadata, and running cargo publish to release on the public registry.", lessons: &[] },
    KTNode { id: "tooling.rustup", parent: Some("tooling"), name: "rustup", blurb: "The toolchain installer/manager: switches stable/beta/nightly compilers, cross targets, and components like clippy.", lessons: &[] },
    KTNode { id: "tooling.clippy", parent: Some("tooling"), name: "Clippy", blurb: "The official linter: hundreds of lints beyond rustc that catch unidiomatic code, likely bugs, and style issues.", lessons: &[] },
    KTNode { id: "tooling.rustfmt", parent: Some("tooling"), name: "rustfmt", blurb: "The official code formatter, run via cargo fmt and configured through a project's rustfmt.toml.", lessons: &[] },
    KTNode { id: "tooling.testing", parent: Some("tooling"), name: "Unit & Integration Tests", blurb: "cargo test's built-in framework: #[test] functions inline in modules, plus black-box tests under tests/.", lessons: &[] },
    KTNode { id: "tooling.testing.doctests", parent: Some("tooling.testing"), name: "Doc Tests", blurb: "Code examples inside /// doc comments that rustdoc extracts and compiles as executable tests.", lessons: &[] },
    KTNode { id: "tooling.testing.nextest", parent: Some("tooling.testing"), name: "cargo-nextest", blurb: "A faster, higher-fidelity test runner with per-test process isolation and clearer output, common in CI in 2026.", lessons: &[] },
    KTNode { id: "tooling.testing.property-based", parent: Some("tooling.testing"), name: "Property-Based Testing", blurb: "proptest and quickcheck generate randomized inputs to find edge cases a hand-written test would miss.", lessons: &[] },
    KTNode { id: "tooling.testing.snapshot", parent: Some("tooling.testing"), name: "Snapshot Testing", blurb: "insta captures a value or output as a snapshot file and fails the test when it drifts from the reviewed baseline.", lessons: &[] },
    KTNode { id: "tooling.benchmarking", parent: Some("tooling"), name: "Benchmarking", blurb: "Measuring code performance repeatably, isolating noise from CPU/OS variance instead of timing with a stopwatch.", lessons: &[] },
    KTNode { id: "tooling.benchmarking.criterion", parent: Some("tooling.benchmarking"), name: "Criterion.rs", blurb: "The standard statistics-driven benchmarking harness, producing HTML reports and flagging performance regressions.", lessons: &[] },
    KTNode { id: "tooling.benchmarking.divan", parent: Some("tooling.benchmarking"), name: "Divan", blurb: "A newer, lighter #[divan::bench]-based benchmarking harness favored for simpler setup than Criterion.", lessons: &[] },
    KTNode { id: "tooling.fuzzing", parent: Some("tooling"), name: "Fuzzing", blurb: "Feeding a function large volumes of random or mutated input to surface crashes, panics, and undefined behavior.", lessons: &[] },
    KTNode { id: "tooling.fuzzing.cargo-fuzz", parent: Some("tooling.fuzzing"), name: "cargo-fuzz", blurb: "The standard entry point for Rust fuzzing, wrapping libFuzzer for coverage-guided input generation.", lessons: &[] },
    KTNode { id: "tooling.fuzzing.afl", parent: Some("tooling.fuzzing"), name: "AFL / LibAFL", blurb: "afl.rs bindings to AFL++ and LibAFL, a Rust-native fuzzing framework now competitive with libFuzzer-based tools.", lessons: &[] },
    KTNode { id: "tooling.miri", parent: Some("tooling"), name: "Miri", blurb: "An interpreter for Rust's mid-level IR that catches undefined behavior, memory errors, and data races in unsafe code.", lessons: &[] },
    KTNode { id: "tooling.rustdoc", parent: Some("tooling"), name: "rustdoc", blurb: "Generates HTML API docs from /// comments; the same engine that renders every crate's page on docs.rs.", lessons: &[] },
    KTNode { id: "tooling.debugging", parent: Some("tooling"), name: "Debugging", blurb: "Inspecting a running Rust program's state: breakpoints, stack traces, variable watches, and structured logging.", lessons: &[] },
    KTNode { id: "tooling.debugging.gdb-lldb", parent: Some("tooling.debugging"), name: "gdb / lldb / rust-gdb", blurb: "Native debuggers with Rust-aware pretty-printers (rust-gdb, rust-lldb) or editor extensions like CodeLLDB.", lessons: &[] },
    KTNode { id: "tooling.debugging.tracing", parent: Some("tooling.debugging"), name: "tracing + tokio-console", blurb: "Structured, async-aware instrumentation with spans and subscribers (tracing), plus tokio-console for live task and resource inspection.", lessons: &[] },
    KTNode { id: "tooling.cross-compilation", parent: Some("tooling"), name: "Cross-Compilation", blurb: "Building a binary for a target triple other than the host, via --target or the cross Docker-based wrapper.", lessons: &[] },
    KTNode { id: "tooling.ci", parent: Some("tooling"), name: "CI Patterns", blurb: "Pipeline conventions: caching with sccache or rust-cache, matrix builds across toolchains, gating on fmt/clippy/test.", lessons: &[] },
    KTNode { id: "tooling.rust-analyzer", parent: Some("tooling"), name: "rust-analyzer", blurb: "The LSP server behind IDE features (autocomplete, inline type errors, refactors) in VS Code, Zed, and other editors.", lessons: &[] },
    KTNode { id: "tooling.supply-chain", parent: Some("tooling"), name: "Supply Chain Security", blurb: "cargo-audit checks CVEs, cargo-deny enforces license/ban policy, cargo-vet requires human-reviewed dependency audits.", lessons: &[] },

    // ── Web, Servers & Data ──
    KTNode { id: "web-data", parent: None, name: "Web, Servers & Data", blurb: "Web frameworks, HTTP, serialization, and databases - the crates behind most production Rust services.", lessons: &[] },
    KTNode { id: "web-data.web-frameworks", parent: Some("web-data"), name: "Web Frameworks", blurb: "Async server frameworks for routing, extractors, and middleware, typically built on tokio and hyper.", lessons: &[] },
    KTNode { id: "web-data.web-frameworks.axum", parent: Some("web-data.web-frameworks"), name: "axum", blurb: "Tower-based router and extractor framework from the Tokio team; the most commonly recommended default in 2026.", lessons: &[] },
    KTNode { id: "web-data.web-frameworks.actix-web", parent: Some("web-data.web-frameworks"), name: "actix-web", blurb: "Actor-model framework known for top HTTP benchmark throughput and a mature, battle-tested middleware ecosystem.", lessons: &[] },
    KTNode { id: "web-data.web-frameworks.rocket", parent: Some("web-data.web-frameworks"), name: "Rocket", blurb: "Ergonomics-first framework with request guards and macro-based routing; slower release cadence than axum.", lessons: &[] },
    KTNode { id: "web-data.web-frameworks.warp", parent: Some("web-data.web-frameworks"), name: "warp", blurb: "Filter-based composable framework built on hyper; still maintained but has lost mindshare to axum since 2023.", lessons: &[] },
    KTNode { id: "web-data.http-stack", parent: Some("web-data"), name: "HTTP Core Stack", blurb: "The low-level async HTTP and middleware layer that most Rust web frameworks and clients are built on.", lessons: &[] },
    KTNode { id: "web-data.http-stack.hyper", parent: Some("web-data.http-stack"), name: "hyper", blurb: "Low-level async HTTP/1 and HTTP/2 library underlying axum, actix-web, reqwest, and tonic.", lessons: &[] },
    KTNode { id: "web-data.http-stack.tower", parent: Some("web-data.http-stack"), name: "tower", blurb: "Service/Layer middleware abstraction (timeouts, retries, rate limiting) shared by axum, tonic, and reqwest.", lessons: &[] },
    KTNode { id: "web-data.http-clients", parent: Some("web-data"), name: "HTTP Clients", blurb: "Crates for making outbound HTTP requests; reqwest (async, hyper-based) is the de facto standard, ureq for sync-only code.", lessons: &[] },
    KTNode { id: "web-data.serialization", parent: Some("web-data"), name: "Serialization Ecosystem", blurb: "serde's derive-based (de)serialization core plus the format crates (JSON, YAML, binary, CSV) built on top of it.", lessons: &[] },
    KTNode { id: "web-data.serialization.serde-json", parent: Some("web-data.serialization"), name: "serde_json", blurb: "The standard JSON crate for Rust: #[derive(Serialize, Deserialize)] plus a dynamic Value type.", lessons: &[49] },
    KTNode { id: "web-data.serialization.yaml", parent: Some("web-data.serialization"), name: "YAML Serialization", blurb: "serde_yaml was archived/deprecated in 2024; serde_yml and serde-saphyr are the community successors as of 2026.", lessons: &[] },
    KTNode { id: "web-data.serialization.bincode", parent: Some("web-data.serialization"), name: "bincode", blurb: "Compact binary serialization for Rust-to-Rust data; v2 dropped implicit serde coupling for a leaner default API.", lessons: &[] },
    KTNode { id: "web-data.serialization.postcard", parent: Some("web-data.serialization"), name: "postcard", blurb: "no_std-friendly binary serde format tuned for embedded and other constrained environments.", lessons: &[] },
    KTNode { id: "web-data.serialization.csv", parent: Some("web-data.serialization"), name: "csv crate", blurb: "Fast CSV reading and writing with optional serde integration for typed records.", lessons: &[47, 48] },
    KTNode { id: "web-data.databases-embedded", parent: Some("web-data"), name: "Embedded Key-Value Stores", blurb: "In-process persistent key-value databases that run inside your Rust process, no server needed.", lessons: &[] },
    KTNode { id: "web-data.databases-embedded.sled", parent: Some("web-data.databases-embedded"), name: "sled", blurb: "Pure-Rust embedded B-tree KV store; long stuck in beta with maintenance concerns, though still widely used.", lessons: &[69, 70, 71, 72, 73, 74] },
    KTNode { id: "web-data.databases-embedded.redb", parent: Some("web-data.databases-embedded"), name: "redb", blurb: "Newer pure-Rust embedded KV store with a stable on-disk format, often cited as sled's 2026 successor.", lessons: &[] },
    KTNode { id: "web-data.databases-relational", parent: Some("web-data"), name: "Relational Databases & ORMs", blurb: "Crates for talking to Postgres/MySQL/SQLite, from raw compile-time-checked SQL to full ORMs.", lessons: &[] },
    KTNode { id: "web-data.databases-relational.sqlx", parent: Some("web-data.databases-relational"), name: "sqlx", blurb: "Async, compile-time-checked raw SQL execution against Postgres, MySQL, and SQLite.", lessons: &[] },
    KTNode { id: "web-data.databases-relational.diesel", parent: Some("web-data.databases-relational"), name: "Diesel", blurb: "Compile-time-safe query builder ORM with a schema DSL generated from database migrations.", lessons: &[] },
    KTNode { id: "web-data.databases-relational.sea-orm", parent: Some("web-data.databases-relational"), name: "SeaORM", blurb: "Async ActiveRecord-style ORM built on sqlx; reached a mature 2.0 release in early 2026.", lessons: &[] },
    KTNode { id: "web-data.grpc-tonic", parent: Some("web-data"), name: "gRPC (tonic)", blurb: "The dominant Rust gRPC implementation, built on hyper and tower, paired with prost for protobuf codegen.", lessons: &[] },
    KTNode { id: "web-data.graphql", parent: Some("web-data"), name: "GraphQL (async-graphql)", blurb: "Code-first GraphQL server crate; the standard choice for exposing a GraphQL API from Rust.", lessons: &[] },
    KTNode { id: "web-data.templating", parent: Some("web-data"), name: "Templating", blurb: "Server-side HTML templating crates for rendering views from Rust web servers.", lessons: &[] },
    KTNode { id: "web-data.templating.askama", parent: Some("web-data.templating"), name: "askama", blurb: "Jinja-like templates compiled to Rust code at build time for type-checked, zero-overhead rendering.", lessons: &[] },
    KTNode { id: "web-data.templating.tera", parent: Some("web-data.templating"), name: "tera", blurb: "Runtime-parsed Jinja2-style templating engine, more dynamic than askama's compile-time approach.", lessons: &[] },
    KTNode { id: "web-data.openapi-docs", parent: Some("web-data"), name: "OpenAPI Docs (utoipa)", blurb: "Derive macros that generate OpenAPI specs from axum/actix handlers and types, code-first.", lessons: &[] },
    KTNode { id: "web-data.websockets", parent: Some("web-data"), name: "WebSockets", blurb: "Real-time bidirectional connections via tokio-tungstenite or a framework's built-in WS upgrade support.", lessons: &[] },
    KTNode { id: "web-data.middleware-auth", parent: Some("web-data"), name: "Middleware & Auth", blurb: "Cross-cutting HTTP concerns: tower-http middleware plus jsonwebtoken/oauth2 crates for authentication.", lessons: &[] },

    // ── Systems, Embedded & Applications ──
    KTNode { id: "systems-embedded", parent: None, name: "Systems, Embedded & Applications", blurb: "CLI tools, embedded/no_std, WebAssembly, GUI, game dev, and other domains Rust reaches into.", lessons: &[] },
    KTNode { id: "systems-embedded.cli-tooling", parent: Some("systems-embedded"), name: "CLI Tooling", blurb: "Building command-line interfaces in Rust, an ecosystem dominated by the clap argument-parsing crate.", lessons: &[53, 54] },
    KTNode { id: "systems-embedded.cli-tooling.clap-derive", parent: Some("systems-embedded.cli-tooling"), name: "clap Derive API", blurb: "Declarative CLI parsing via #[derive(Parser)], the modern default that replaced structopt.", lessons: &[53] },
    KTNode { id: "systems-embedded.cli-tooling.structopt-legacy", parent: Some("systems-embedded.cli-tooling"), name: "structopt (legacy)", blurb: "Predecessor derive API for clap v2; folded into clap v3+ and now in maintenance-only mode.", lessons: &[] },
    KTNode { id: "systems-embedded.embedded-hal", parent: Some("systems-embedded"), name: "embedded-hal", blurb: "Trait-based hardware abstraction layer so one driver crate can target many microcontrollers, alongside peripheral access crates (PACs).", lessons: &[] },
    KTNode { id: "systems-embedded.embassy", parent: Some("systems-embedded"), name: "Embassy", blurb: "Async embedded framework using Rust async/await as a lightweight alternative to a traditional RTOS.", lessons: &[] },
    KTNode { id: "systems-embedded.rtic", parent: Some("systems-embedded"), name: "RTIC", blurb: "Real-Time Interrupt-driven Concurrency framework with priority-based resource locks, no OS kernel.", lessons: &[] },
    KTNode { id: "systems-embedded.no-std-programming", parent: Some("systems-embedded"), name: "no_std Programming", blurb: "Writing Rust without the standard library for bare-metal targets, using only core and alloc.", lessons: &[] },
    KTNode { id: "systems-embedded.embedded-tooling", parent: Some("systems-embedded"), name: "Embedded Dev Tooling", blurb: "Flashing, debugging, and logging tools built around microcontroller development workflows.", lessons: &[] },
    KTNode { id: "systems-embedded.embedded-tooling.probe-rs", parent: Some("systems-embedded.embedded-tooling"), name: "probe-rs", blurb: "Rust-native debugging and flashing toolkit for ARM/RISC-V chips, increasingly replacing OpenOCD.", lessons: &[] },
    KTNode { id: "systems-embedded.embedded-tooling.defmt", parent: Some("systems-embedded.embedded-tooling"), name: "defmt Logging", blurb: "Deferred-formatting logging framework that keeps firmware binary size tiny on constrained MCUs.", lessons: &[] },
    KTNode { id: "systems-embedded.wasm", parent: Some("systems-embedded"), name: "WebAssembly", blurb: "Compiling Rust to wasm32 targets for browsers, edge runtimes, and sandboxed plugin systems.", lessons: &[] },
    KTNode { id: "systems-embedded.wasm.wasm-bindgen", parent: Some("systems-embedded.wasm"), name: "wasm-bindgen", blurb: "Generates JS/Rust bindings for browser wasm targets; wasm-pack wraps it into a build pipeline.", lessons: &[] },
    KTNode { id: "systems-embedded.wasm.wasmtime", parent: Some("systems-embedded.wasm"), name: "Wasmtime & Component Model", blurb: "Standalone WASI runtime for server-side wasm, driving the emerging WASI 0.3 Component Model.", lessons: &[] },
    KTNode { id: "systems-embedded.gui", parent: Some("systems-embedded"), name: "Desktop GUI Frameworks", blurb: "Native and webview-based desktop application frameworks written in Rust.", lessons: &[] },
    KTNode { id: "systems-embedded.gui.egui", parent: Some("systems-embedded.gui"), name: "egui", blurb: "Immediate-mode GUI library, the fastest way to prototype a cross-platform Rust desktop tool.", lessons: &[] },
    KTNode { id: "systems-embedded.gui.iced", parent: Some("systems-embedded.gui"), name: "iced", blurb: "Elm-inspired retained-mode GUI framework built around a message/update architecture.", lessons: &[] },
    KTNode { id: "systems-embedded.gui.tauri", parent: Some("systems-embedded.gui"), name: "Tauri", blurb: "Rust-backed alternative to Electron that renders the UI in the OS's native webview, now with mobile targets.", lessons: &[] },
    KTNode { id: "systems-embedded.gui.gtk-rs", parent: Some("systems-embedded.gui"), name: "gtk-rs and Relm4", blurb: "Rust bindings for GTK4, with Relm4 layering an Elm-style component model on top.", lessons: &[] },
    KTNode { id: "systems-embedded.game-dev", parent: Some("systems-embedded"), name: "Game Development", blurb: "Game engines and frameworks written in Rust, from full ECS engines to lightweight 2D libraries.", lessons: &[] },
    KTNode { id: "systems-embedded.game-dev.bevy", parent: Some("systems-embedded.game-dev"), name: "Bevy", blurb: "Data-driven ECS game engine, the most active Rust engine with a fast quarterly release cadence.", lessons: &[] },
    KTNode { id: "systems-embedded.game-dev.ggez-macroquad", parent: Some("systems-embedded.game-dev"), name: "ggez / Macroquad", blurb: "Lightweight 2D game frameworks often preferred over Bevy's larger ECS for jams and simple games.", lessons: &[] },
    KTNode { id: "systems-embedded.os-dev", parent: Some("systems-embedded"), name: "OS & Kernel Development", blurb: "Writing operating systems and kernel-level code in Rust, from hobby kernels to production OSes.", lessons: &[] },
    KTNode { id: "systems-embedded.os-dev.redox", parent: Some("systems-embedded.os-dev"), name: "Redox OS", blurb: "Unix-like microkernel OS written in Rust, now able to self-host its own Rust toolchain.", lessons: &[] },
    KTNode { id: "systems-embedded.os-dev.bare-metal-kernel", parent: Some("systems-embedded.os-dev"), name: "Bare-Metal Kernel Writing", blurb: "Building a hobby x86/ARM kernel from scratch with #[no_std], custom targets, and a bootloader crate.", lessons: &[] },
    KTNode { id: "systems-embedded.safety-verification", parent: Some("systems-embedded"), name: "Formal Verification & Safety-Critical", blurb: "Tools that prove correctness or absence of undefined behavior for high-assurance Rust code.", lessons: &[] },
    KTNode { id: "systems-embedded.safety-verification.kani", parent: Some("systems-embedded.safety-verification"), name: "Kani", blurb: "AWS's bounded model checker for Rust, run in production CI on projects like Firecracker.", lessons: &[] },
    KTNode { id: "systems-embedded.safety-verification.prusti", parent: Some("systems-embedded.safety-verification"), name: "Prusti", blurb: "ETH Zurich verifier that proves functional correctness of Rust code via annotated contracts.", lessons: &[] },
    KTNode { id: "systems-embedded.safety-verification.ferrocene", parent: Some("systems-embedded.safety-verification"), name: "Ferrocene", blurb: "TUV-qualified Rust toolchain certified for ISO 26262 and IEC 61508 safety-critical use.", lessons: &[] },
    KTNode { id: "systems-embedded.scripting-embedding", parent: Some("systems-embedded"), name: "Scripting & Embedding", blurb: "Embedding a scripting language, such as Rhai or Lua via mlua, inside a Rust host application.", lessons: &[] },
];
